---
title: "CN_CTCF_Npas4"
author: "Viviana"
date: '2022-07-01'
output: html_document
editor_options: 
  chunk_output_type: console
---


#Analysis of CTCF binding in Arc in Cortical Neurons 

```{r}

suppressPackageStartupMessages({
  library(AnnotationHub)
  library(Rsubread)
  library(rtracklayer)
  library(Biostrings)
  library(Rfastp)
  library(epiwraps)
  library(GEOquery)
  library(GenomicRanges)
  library(IRanges)
  library(ChIPpeakAnno)
  library(ggplot2)
  library(gridExtra)

})



```


```{r}

#Import tracks CN 

tracks_CN_CTCF<- rtracklayer::import('CN/tracks/GSE96107_CN_CTCF.bw')
```


```{r}
peaks_CN_CTCF<- rtracklayer::import('CN/peaks/GSE96107_CN_CTCF.IDR0.05.filt.narrowPeak')
```


```{r}


library(Gviz)

ideogram<- IdeogramTrack("chr19", "mm10")
axis<- GenomeAxisTrack()

cover_track_CTCF_CN<-DataTrack(tracks_CN_CTCF, window= 100000,type= "h", name="Coverage")

peak_track_CTCF_CN<-AnnotationTrack(peaks_CN_CTCF,name="Peaks")

library("TxDb.Mmusculus.UCSC.mm10.knownGene")
tx<-GeneRegionTrack(TxDb.Mmusculus.UCSC.mm10.knownGene ,chromosome = "chr19",start  = 4900000, end= 5004439, name="Genes")

plotTracks(list(ideogram,cover_track_CTCF_CN, peak_track_CTCF_CN,tx, axis),from = 4900000, to= 5004439, chromosome = "chr19",main= "CTCF binding around Npas4 in CN", cex.main=1.5)
```
